name: Scaffold PR Setup
inputs:
  GH_NPM_TOKEN:
    required: true
    type: string
  github_token:
    required: false
    type: string
    default: ${{ github.token }}
  checkout_ref:
    required: false
    type: string
  skip_install:
    required: true
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        ref: ${{ inputs.checkout_ref }}

    - uses: actions/setup-node@v2
      with:
        node-version: 16.13.1
        cache: 'yarn'

    - name: Install Immutable Dependencies
      if: ${{ inputs.skip_install == 'false' }}
      env:
        GH_NPM_TOKEN: ${{ inputs.GH_NPM_TOKEN }}
      run: yarn install --immutable
      shell: bash
